CREATE DATABASE [HeThongThiTracNghiem];
GO

USE [HeThongThiTracNghiem];
GO

-- NHÓM BẢNG HỆ THỐNG - DANH MỤC 

-- Table: Privileges (User permissions) - Phân quyền người dùng 
CREATE TABLE Privileges (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100),
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    STT INT
);

-- Table: Industries (Academic industries) - Ngành học 
CREATE TABLE Industries (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAMEINDUSTRY NVARCHAR(100),
    CODE NVARCHAR(50),
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    STT INT
);

-- Table: Courses (Courses) - Khóa học
CREATE TABLE Courses (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAMECOURSE NVARCHAR(100),
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    STT INT
);

-- Table: Semesters (Academic semesters) - Học kỳ 
CREATE TABLE Semesters (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSEID INT,
    NAMESEMESTER NVARCHAR(100),
    STARTDAY DATE,
    ENDDAY DATE,
    CREATEAT DATETIME,
    STT INT,
    CONSTRAINT FK_Semesters_Courses
        FOREIGN KEY (COURSEID) REFERENCES Courses(ID)
);

-- NHÓM BẢNG NGƯỜI DÙNG - LỚP HỌC

-- Table: AccountUsers (System users) - Tài khoản hệ thống 
CREATE TABLE AccountUsers (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAMEUSER NVARCHAR(100),
    ACCOUNT NVARCHAR(100),
    PASS NVARCHAR(255),
    IMS NVARCHAR(50),
    SEX NVARCHAR(10),
    EMAIL NVARCHAR(100),
    ROLE NVARCHAR(50),
    CREATEAT DATETIME,
    STT INT
);

-- Table: Classes (Classes) - Lớp học 
CREATE TABLE Classes (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SEMESTERID INT,
    INDUSTRYID INT,
    IDTEACHER INT,
    KEYCLASS NVARCHAR(50),
    NAMECLASS NVARCHAR(100),
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    CREATEDATE DATETIME,
    STT INT,
    CONSTRAINT FK_Classes_Semesters FOREIGN KEY (SEMESTERID) REFERENCES Semesters(ID),
    CONSTRAINT FK_Classes_Industries FOREIGN KEY (INDUSTRYID) REFERENCES Industries(ID),
    CONSTRAINT FK_Classes_Teacher FOREIGN KEY (IDTEACHER) REFERENCES AccountUsers(ID)
);

-- Table: AccountStudents (Student accounts) - Tài khoản sinh viên
CREATE TABLE AccountStudents (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDINDUSTRY INT,
    IDCORUSE INT,
    NAMESTUDENT NVARCHAR(100),
    ACCOUNT NVARCHAR(100),
    PASS NVARCHAR(255),
    SEX NVARCHAR(10),
    EMAIL NVARCHAR(100),
    BIRTHDAY DATE,
    ROLE NVARCHAR(50),
    CREATEAT DATETIME,
    CREATEDATE DATETIME,
    STT INT,
    CURRENTSESSION NVARCHAR(100),
    LASTLOGINTIME DATETIME,
    PASSWORDRESETTOKEN NVARCHAR(255),
    TOKENEXPIRY DATETIME,
    CONSTRAINT FK_AccountStudents_Industries
        FOREIGN KEY (IDINDUSTRY) REFERENCES Industries(ID)
);


-- Table: StudentOnClasses (Students enrolled in classes) - Sinh viên - Lớp học
CREATE TABLE StudentOnClasses (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDSTUDENT INT,
    IDCLASS INT,
    CONSTRAINT FK_SOC_Student FOREIGN KEY (IDSTUDENT) REFERENCES AccountStudents(ID),
    CONSTRAINT FK_SOC_Class FOREIGN KEY (IDCLASS) REFERENCES Classes(ID)
);

-- NHÓM BẢNG MÔN HỌC - CÂU HỎI 
-- Table: Subjects (Subjects) - Môn học 
CREATE TABLE Subjects (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDSEMESTER INT,
    CODE NVARCHAR(50),
    NAMESUBJECT NVARCHAR(100),
    TINCHI INT,
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    CREATEDATE DATETIME,
    STT INT,
    CONSTRAINT FK_Subjects_Semesters FOREIGN KEY (IDSEMESTER) REFERENCES Semesters(ID)
);

-- Table: Chapters (Subject chapters) - Chương 
CREATE TABLE Chapters (
    IDCHAPTER INT IDENTITY(1,1) PRIMARY KEY,
    IDSUBJECT INT,
    NAMECHAPTER NVARCHAR(100),
    CREATEAT DATETIME,
    STT INT,
    CONSTRAINT FK_Chapters_Subjects FOREIGN KEY (IDSUBJECT) REFERENCES Subjects(ID)
);

-- Table: SubjectTeachers (Subjects assigned to teachers) - Giáo Viên - Môn học
CREATE TABLE SubjectByTeachers (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDSUBJECT INT,
    IDTEACHER INT,
    CREATEAT DATETIME,
    STT INT,
    CONSTRAINT FK_SubjectTeachers_Subjects
        FOREIGN KEY (IDSUBJECT) REFERENCES Subjects(ID),
    CONSTRAINT FK_SubjectTeachers_Teachers
        FOREIGN KEY (IDTEACHER) REFERENCES AccountUsers(ID)
);

-- Table: Questions (Question bank) - Câu hỏi 
CREATE TABLE Questions (
    IDQUESTION INT IDENTITY(1,1) PRIMARY KEY,
    QUESTIONTEXT NVARCHAR(MAX),
    QUESTIONTYPE NVARCHAR(50),
    DIFFICULTY INT,
    IDCHAPTER INT,
    CREATEAT DATETIME,
    CREATEDATE DATETIME,
    STT INT,
    CONSTRAINT FK_Questions_Chapters FOREIGN KEY (IDCHAPTER) REFERENCES Chapters(IDCHAPTER)
);

-- Table: Answers (Answers of questions) - Đáp án  
CREATE TABLE Answers (
    IDANSWER INT IDENTITY(1,1) PRIMARY KEY,
    IDQUESTION INT,
    ANSWERTEXT NVARCHAR(MAX),
    ISCORRECT BIT,
    ANSWERTYPE NVARCHAR(50),
    EXPLANATION NVARCHAR(MAX),
    CONSTRAINT FK_Answers_Questions FOREIGN KEY (IDQUESTION) REFERENCES Questions(IDQUESTION)
);

-- NHÓM THI 
-- Table: Exams (Examinations) - Đề thi
CREATE TABLE Exams (
    IDEXAM INT IDENTITY(1,1) PRIMARY KEY,
    IDSUBJECT INT,
    IDSEMESTER INT,
    IDCLASS INT,
    IDTEACHER INT,
    NAMEEXAM NVARCHAR(100),
    DESCRIBE NVARCHAR(255),
    CREATEAT DATETIME,
    CREATEDATE DATETIME,
    CREATESTART DATETIME,
    CREATEEND DATETIME,
    ASSIGNMENTTIME INT,
    NUMBER INT,
    PASSWORD NVARCHAR(50),
    STATUS NVARCHAR(50),
    MIXQUESTION BIT,
    MIXANSWER BIT,
    SHOWPOINT BIT,
    CONSTRAINT FK_Exams_Subjects FOREIGN KEY (IDSUBJECT) REFERENCES Subjects(ID),
    CONSTRAINT FK_Exams_Classes FOREIGN KEY (IDCLASS) REFERENCES Classes(ID),
    CONSTRAINT FK_Exams_Teacher FOREIGN KEY (IDTEACHER) REFERENCES AccountUsers(ID)
);

-- Table: QuestionsToExams (Mapping questions to exams) - Câu hỏi - Đề Thi
CREATE TABLE QuestionsToExams (
    IDQUESTIONTOEXAM INT IDENTITY(1,1) PRIMARY KEY,
    IDEXAM INT,
    IDQUESTION INT,
    STATUS NVARCHAR(50),
    CONSTRAINT FK_QTE_Exams FOREIGN KEY (IDEXAM) REFERENCES Exams(IDEXAM),
    CONSTRAINT FK_QTE_Questions FOREIGN KEY (IDQUESTION) REFERENCES Questions(IDQUESTION)
);

-- Table: ExamRecords (Exam records) - Kết quả thi
CREATE TABLE ExamRecords (
    RECORDID INT IDENTITY(1,1) PRIMARY KEY,
    STUDENTID INT,
    EXAMID INT,
    STARTTIME DATETIME,
    ENDTIME DATETIME,
    ATTEMPTCOUNT INT,
    TOTALSCORE FLOAT,
    ISCOMPLETED BIT,
    CONSTRAINT FK_ExamRecords_Exam FOREIGN KEY (EXAMID) REFERENCES Exams(IDEXAM)
);

-- Table: TempAnswers (Temporary student answers) - Bài làm tạm thời 
CREATE TABLE TempAnswers (
    TEMPANSWERID INT IDENTITY(1,1) PRIMARY KEY,
    EXAMID INT,
    STUDENTID INT,
    QUESTIONID INT,
    ANSWERID INT,
    SUBMITTED BIT,
    DATECREATE DATETIME,
    ANSWERSELECT NVARCHAR(255),
    ATTEMPTCOUNT INT,
    CONSTRAINT FK_TempAnswers_Exam FOREIGN KEY (EXAMID) REFERENCES Exams(IDEXAM),
    CONSTRAINT FK_TempAnswers_Question FOREIGN KEY (QUESTIONID) REFERENCES Questions(IDQUESTION),
    CONSTRAINT FK_TempAnswers_Answer FOREIGN KEY (ANSWERID) REFERENCES Answers(IDANSWER)
);



